version: "3.9"

services:
  db:
    image: postgres:15
    container_name: balance_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: balance
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: balance_app
    command: >
      sh -c "poetry run alembic upgrade head &&
             poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  grpc:
    build:
      context: .
    container_name: balance_grpc
    command: poetry run python -m app.grpc.grpc_server
    ports:
      - "50051:50051"
    depends_on:
      - db

volumes:
  db_data:
