# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings
from app.grpc import balance_pb2 as balance__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in balance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BalanceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChangeBalance = channel.unary_unary(
                '/balance.BalanceService/ChangeBalance',
                request_serializer=balance__pb2.ChangeBalanceRequest.SerializeToString,
                response_deserializer=balance__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.OpenTransaction = channel.unary_unary(
                '/balance.BalanceService/OpenTransaction',
                request_serializer=balance__pb2.OpenTransactionRequest.SerializeToString,
                response_deserializer=balance__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.CommitTransaction = channel.unary_unary(
                '/balance.BalanceService/CommitTransaction',
                request_serializer=balance__pb2.TransactionActionRequest.SerializeToString,
                response_deserializer=balance__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.CancelTransaction = channel.unary_unary(
                '/balance.BalanceService/CancelTransaction',
                request_serializer=balance__pb2.TransactionActionRequest.SerializeToString,
                response_deserializer=balance__pb2.BalanceResponse.FromString,
                _registered_method=True)


class BalanceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChangeBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BalanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChangeBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeBalance,
                    request_deserializer=balance__pb2.ChangeBalanceRequest.FromString,
                    response_serializer=balance__pb2.BalanceResponse.SerializeToString,
            ),
            'OpenTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenTransaction,
                    request_deserializer=balance__pb2.OpenTransactionRequest.FromString,
                    response_serializer=balance__pb2.TransactionResponse.SerializeToString,
            ),
            'CommitTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitTransaction,
                    request_deserializer=balance__pb2.TransactionActionRequest.FromString,
                    response_serializer=balance__pb2.BalanceResponse.SerializeToString,
            ),
            'CancelTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTransaction,
                    request_deserializer=balance__pb2.TransactionActionRequest.FromString,
                    response_serializer=balance__pb2.BalanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'balance.BalanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('balance.BalanceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BalanceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChangeBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/balance.BalanceService/ChangeBalance',
            balance__pb2.ChangeBalanceRequest.SerializeToString,
            balance__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/balance.BalanceService/OpenTransaction',
            balance__pb2.OpenTransactionRequest.SerializeToString,
            balance__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/balance.BalanceService/CommitTransaction',
            balance__pb2.TransactionActionRequest.SerializeToString,
            balance__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/balance.BalanceService/CancelTransaction',
            balance__pb2.TransactionActionRequest.SerializeToString,
            balance__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
