# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: balance.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'balance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbalance.proto\x12\x07\x62\x61lance\x1a\x1bgoogle/protobuf/empty.proto\"Q\n\x14\x43hangeBalanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x15\n\rdelta_current\x18\x02 \x01(\x01\x12\x11\n\tdelta_max\x18\x03 \x01(\x01\"R\n\x16OpenTransactionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x17\n\x0ftimeout_seconds\x18\x03 \x01(\x05\"2\n\x18TransactionActionRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"!\n\x0f\x42\x61lanceResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"=\n\x13TransactionResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2\xd0\x02\n\x0e\x42\x61lanceService\x12H\n\rChangeBalance\x12\x1d.balance.ChangeBalanceRequest\x1a\x18.balance.BalanceResponse\x12P\n\x0fOpenTransaction\x12\x1f.balance.OpenTransactionRequest\x1a\x1c.balance.TransactionResponse\x12P\n\x11\x43ommitTransaction\x12!.balance.TransactionActionRequest\x1a\x18.balance.BalanceResponse\x12P\n\x11\x43\x61ncelTransaction\x12!.balance.TransactionActionRequest\x1a\x18.balance.BalanceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'balance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANGEBALANCEREQUEST']._serialized_start=55
  _globals['_CHANGEBALANCEREQUEST']._serialized_end=136
  _globals['_OPENTRANSACTIONREQUEST']._serialized_start=138
  _globals['_OPENTRANSACTIONREQUEST']._serialized_end=220
  _globals['_TRANSACTIONACTIONREQUEST']._serialized_start=222
  _globals['_TRANSACTIONACTIONREQUEST']._serialized_end=272
  _globals['_BALANCERESPONSE']._serialized_start=274
  _globals['_BALANCERESPONSE']._serialized_end=307
  _globals['_TRANSACTIONRESPONSE']._serialized_start=309
  _globals['_TRANSACTIONRESPONSE']._serialized_end=370
  _globals['_BALANCESERVICE']._serialized_start=373
  _globals['_BALANCESERVICE']._serialized_end=709
# @@protoc_insertion_point(module_scope)
